version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_admin
    environment:
      MYSQL_ROOT_PASSWORD: "superpass"
      MYSQL_DATABASE: "admin_practice"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user123"
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_lab
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "superpass"
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  mysql_data:
